### PR TITLE
Add support for Coq 8.10, 8.11; remove support for Coq 8.9

### LINKED ISSUE #4: Support for Coq 8.10
We should branch the 8.9 support and add support for 8.10 and newer (requires changing .ml4 to .mlg).  We should probably also add this to Coq's CI

### PR DESCRIPTION
**Pull request by JasonGross**
After we merge this, we should release v0.1.2

Closes #4

### CODE REVIEW

**Comment by JasonGross** [comment]
@liyishuai Do you want to take a look at this, or should I merge it directly?

**Review by liyishuai — APPROVED** [review]

**Comment by liyishuai** [comment]
Did you have CircleCI enabled on your fork?

**Comment by JasonGross** [comment]
> Did you have CircleCI enabled on your fork?

No, I don't think so.  How do I enable it?

**Comment by JasonGross** [comment]
Also, are you going to release v0.1.2 and update opam, or shall I plan on doing it tomorrow?

**Comment by liyishuai** [comment]
Try one of these links: https://onboarding.circleci.com/project-dashboard/github/JasonGross https://circleci.com/add-projects/gh/JasonGross

I'm going offline. Feel free to release.

**Pull request merged**
