### PR TITLE
adapt to coq/coq#15220

### PR DESCRIPTION
**Pull request by gares**
To be merge when https://github.com/coq/coq/pull/15220 is.

### CODE REVIEW

**Review by liyishuai — APPROVED** [review]

**Comment by JasonGross** [comment]
Is this backwards compatible?  If not, we should tag a release and update the opam package, etc

**Comment by gares** [comment]
No it is not backward compatible.

**Comment by liyishuai** [comment]
It can be: gares/coq-simple-io@010ff1dae91ab09af9b38c7ef21f96e835bbfa98

**Comment by gares** [comment]
your commit should show up here, weird github...

**Review by liyishuai — APPROVED** [review]
Now backwards compatible; depends on package [Cppo](https://github.com/ocaml-community/cppo), which is not so heavy.

**Comment by SkySkimmer** [comment]
Please merge now

**Pull request merged**
