### PR TITLE
Switch license to MPL

### PR DESCRIPTION
**Pull request by liyishuai**
I've noticed that this repo uses LGPL which is no longer recommended by the community. Should we switch license before having more contributors?

### CODE REVIEW

**Comment by JasonGross** [comment]
Why the MPL rather than MIT or BSD?

**Comment by liyishuai** [comment]
The current LGPL is weak-copyleft, so I proposed MPL which is still weak-copyleft but easier to clarify.

**Review by Zimmi48 — APPROVED** [review]
I do not think that my contributions have much value, but I'm formally approving this change of license to MPL (or MIT or BSD) nonetheless. The most important voice to hear is of course from @herbelin since he is the original author of this code.

**Comment by herbelin** [comment]
I'm ok with licensing the plugin as MPL or MIT (or BSD).

**Comment by SkySkimmer** [comment]
Shouldn't plugins be lgpl so that they can exchange code with coq?

**Comment by herbelin** [comment]
> Shouldn't plugins be lgpl so that they can exchange code with coq?

What about double licensing then?

**Comment by Zimmi48** [comment]
>Shouldn't plugins be lgpl so that they can exchange code with coq?

That's a fair question.

>What about double licensing then?

This would work for the external plugin to Coq path, but not for the other way (I don't know if it's really important though).

**Comment by liyishuai** [comment]
Do we need double licensing for MPL code in LGPL project?

**Comment by Zimmi48** [comment]
> Do we need double licensing for MPL code in LGPL project?

No, actually, you're right. Since MPL 2.0 is explictly designed to be (L)GPL-compatible, we don't.

**Review by JasonGross — APPROVED** [review]

**Comment by liyishuai** [comment]
I can foresee migrating code from here to Coq repo, but not backwards.
Propose merging on Monday if no other concerns arise.

**Pull request merged**
